---
name: ci
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: yaml-lint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.github/ci/yamllint.yml'
          yamllint_strict: true
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
          args: -c .github/ci/golangci.yml
  build:
    name: build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Build
        run: go build -race  ./...
      - name: Test
        run: go test -race ./...
